name: quicklz
description: QuickLZ号称是世界上速度最快的压缩库，使用简单，易于集成。
keywords:                                   # 多标签
  - quicklz
author:
  name: hongming
license: GPLv3
homepage: https://github.com/yoc-components/quicklz

depends:                                    # 该组件依赖其他的组件

build_config:
  include:
  cflag: ''                                 # C 编译器所需要要的编译参数
  cxxflag: ''                               # CXX 编译器所需要要的编译参数
  asmflag: ''                               # 汇编器所需要要参数
  # define:                                   # 宏定义

source_file:
  - "*.c"                                   # 支持通配符与正则表达示

install:
  - dest: "include/"
    source:
      - quicklz.h
      - quicklz.c
